# Generated by Django 2.2.5 on 2020-08-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picname',
            field=models.TextField(default='-', max_length=12),
        ),
        migrations.AddField(
            model_name='product',
            name='picurl',
            field=models.TextField(default='-'),
        ),
    ]
