# Generated by Django 2.2.5 on 2020-09-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200830_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='artist',
            field=models.TextField(default='-', max_length=100),
        ),
    ]
