# Generated by Django 2.2.5 on 2020-09-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categ_name',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
