# Generated by Django 2.2.5 on 2020-04-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('utxt', models.TextField()),
                ('set_name', models.TextField(default='-')),
            ],
        ),
    ]
