# Generated by Django 2.2.5 on 2020-03-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('catname', models.CharField(max_length=30)),
                ('catid', models.IntegerField()),
                ('set_name', models.TextField(default='-')),
            ],
        ),
    ]
