# Generated by Django 2.2.5 on 2020-09-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='-', max_length=200),
        ),
    ]
