# Generated by Django 2.2.5 on 2020-03-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200317_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pic',
            field=models.TextField(default='-', max_length=12),
        ),
    ]
