# Generated by Django 2.2.5 on 2020-10-31 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picurl1', models.TextField(default='-')),
                ('picurl2', models.TextField(default='-')),
                ('picurl3', models.TextField(default='-')),
                ('post_date', models.DateField(default=datetime.date(2020, 10, 31))),
            ],
        ),
    ]
