# Generated by Django 2.2.5 on 2020-03-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='set_name',
            field=models.TextField(default='-'),
        ),
    ]
