# Generated by Django 2.2.5 on 2020-08-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('count', models.IntegerField(default=0)),
                ('set_name', models.TextField(default='-')),
            ],
        ),
    ]
