# Generated by Django 2.2.5 on 2020-05-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_main_abouttxt'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='seo_keywords',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='main',
            name='seo_txt',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
